/**
 *
 * $Id$
 */
package co.edu.uniandes.diff.metamodel.diff.validation;

import co.edu.uniandes.diff.metamodel.diff.Simple;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link co.edu.uniandes.diff.metamodel.diff.Complex}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexValidator {
	boolean validate();

	boolean validateSimpleDiffs(EList<Simple> value);
}
