/**
 *
 * $Id$
 */
package co.edu.uniandes.diff.metamodel.diff.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link co.edu.uniandes.diff.metamodel.diff.ElementReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementReferenceValidator {
	boolean validate();

	boolean validateEObject(Object value);
	boolean validateLineNumber(BigInteger value);
	boolean validateXpath(String value);
}
