/**
 *
 * $Id$
 */
package core.validation;

import core.Info;
import core.Path;
import core.Response;
import core.Schema;
import core.SchemeType;
import core.SecuritySchema;
import core.Tag;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link core.API}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface APIValidator {
	boolean validate();

	boolean validateSwagger(String value);
	boolean validateInfo(Info value);
	boolean validateHost(String value);
	boolean validateBasePath(String value);
	boolean validateSchemes(EList<SchemeType> value);
	boolean validateConsumes(EList<String> value);
	boolean validateProduces(EList<String> value);
	boolean validatePaths(EList<Path> value);
	boolean validateDefinitions(EList<Schema> value);
	boolean validateResponses(EList<Response> value);
	boolean validateSecurityDefinitions(EList<SecuritySchema> value);
	boolean validateTags(EList<Tag> value);
}
