/**
 *
 * $Id$
 */
package core.validation;

import core.CollectionFormat;
import core.ItemsDefinition;

/**
 * A sample validator interface for {@link core.ArrayContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArrayContextValidator {
	boolean validate();

	boolean validateCollectionFormat(CollectionFormat value);
	boolean validateItems(ItemsDefinition value);
}
