/**
 *
 * $Id$
 */
package core.validation;

import core.Contact;
import core.License;

/**
 * A sample validator interface for {@link core.Info}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InfoValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateDescription(String value);
	boolean validateTermsOfServices(String value);
	boolean validateContact(Contact value);
	boolean validateLicense(License value);
	boolean validateVersion(String value);
}
