/**
 *
 * $Id$
 */
package core.validation;

import core.JSONDataType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link core.JSONSchemaSubset}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JSONSchemaSubsetValidator {
	boolean validate();

	boolean validateType(JSONDataType value);
	boolean validateFormat(String value);
	boolean validateDescription(String value);
	boolean validateMaximum(Double value);
	boolean validateExclusiveMaximum(Boolean value);
	boolean validateMinimum(Double value);
	boolean validateExclusiveMinimum(Boolean value);
	boolean validateMaxLength(Integer value);
	boolean validateMinLength(Integer value);
	boolean validatePattern(String value);
	boolean validateMaxItems(Integer value);
	boolean validateMinItems(Integer value);
	boolean validateUniqueItems(Boolean value);
	boolean validateEnum(EList<String> value);
	boolean validateDefault(String value);
	boolean validateMultipleOf(double value);
}
