/**
 *
 * $Id$
 */
package core.validation;

import core.Path;
import core.Response;
import core.SchemeType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link core.Operation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationValidator {
	boolean validate();

	boolean validateTagReferences(EList<String> value);
	boolean validateSummary(String value);
	boolean validateDescription(String value);
	boolean validateOperationId(String value);
	boolean validateConsumes(EList<String> value);
	boolean validateProduces(EList<String> value);
	boolean validateResponses(EList<Response> value);
	boolean validateSchemes(EList<SchemeType> value);
	boolean validateDeprecated(Boolean value);
	boolean validatePath(Path value);
}
