/**
 *
 * $Id$
 */
package core.validation;

import core.ParameterLocation;
import core.ParamterDeclaringContext;

/**
 * A sample validator interface for {@link core.Parameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateLocation(ParameterLocation value);
	boolean validateRequired(Boolean value);
	boolean validateAllowEmplyValue(Boolean value);
	boolean validateReferenceName(String value);
	boolean validateDeclaringContext(ParamterDeclaringContext value);
}
