/**
 *
 * $Id$
 */
package core.validation;

import core.Operation;

/**
 * A sample validator interface for {@link core.Path}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PathValidator {
	boolean validate();

	boolean validatePattern(String value);
	boolean validateGet(Operation value);
	boolean validatePut(Operation value);
	boolean validatePost(Operation value);
	boolean validateDelete(Operation value);
	boolean validateOptions(Operation value);
	boolean validateHead(Operation value);
	boolean validatePatch(Operation value);
}
