/**
 *
 * $Id$
 */
package core.validation;

import core.Example;
import core.Header;
import core.ResponseDeclaringContext;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link core.Response}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResponseValidator {
	boolean validate();

	boolean validateDescription(String value);
	boolean validateHeaders(EList<Header> value);
	boolean validateExamples(EList<Example> value);
	boolean validateCode(String value);
	boolean validateDeclaringContext(ResponseDeclaringContext value);
	boolean validateReferenceName(String value);
}
