/**
 *
 * $Id$
 */
package core.validation;

import core.API;
import core.Parameter;
import core.Response;
import core.Schema;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link core.Root}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootValidator {
	boolean validate();

	boolean validateApi(API value);
	boolean validateParamters(EList<Parameter> value);
	boolean validateSchemas(EList<Schema> value);
	boolean validateResponses(EList<Response> value);
}
